import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  docsSidebar: [
    { type: 'autogenerated', dirName: '.' },
    {
      type: 'category',
      label: 'Examples',
      link: {
        type: 'generated-index',
        description: 'View examples of how to use the mediainfo.js library.',
      },
      items: [
        {
          type: 'link',
          label: 'Browser (via CDN)',
          href: 'https://github.com/buzz/mediainfo.js/tree/main/examples/browser-umd',
          description: 'A simple static HTML page',
        },
        {
          type: 'link',
          label: 'CodePen (via CDN)',
          href: 'https://codepen.io/buzzone/pen/eYNjJrx',
          description: 'CodePen with mediainfo.js from CDN',
        },
        {
          type: 'link',
          label: 'Vite/React',
          href: 'https://github.com/buzz/mediainfo.js/tree/main/examples/vite-react',
          description: 'A sample React project using Vite',
        },
        {
          type: 'link',
          label: 'Webpack/React',
          href: 'https://github.com/buzz/mediainfo.js/tree/main/examples/webpack-react',
          description: 'A sample React project using webpack',
        },
        {
          type: 'link',
          label: 'Angular',
          href: 'https://github.com/buzz/mediainfo.js/tree/main/examples/angular',
          description: 'A sample Angular project',
        },
        {
          type: 'link',
          label: 'Node.js',
          href: 'https://github.com/buzz/mediainfo.js/blob/main/src/cli.ts',
          description: 'The mediainfo.js CLI program',
        },
      ],
    },
  ],
}

export default sidebars
