import { join, resolve } from 'path'

const PROJECT_DIR = resolve(__dirname, '..')
const SRC_DIR = join(PROJECT_DIR, 'src')
const DIST_DIR = join(PROJECT_DIR, 'dist')
const BUILD_DIR = join(PROJECT_DIR, 'build')
const VENDOR_DIR = join(BUILD_DIR, 'vendor')
const ZLIB_DIR = join(VENDOR_DIR, 'Shared', 'Source')

const LIBMEDIAINFO_VERSION = '23.07'
const LIBZEN_VERSION = '0.4.41'
const ZLIB_VERSION = '1.2.13'

const CFLAGS = '-Oz -DUNICODE -g0'
const CXXFLAGS = '-Oz -DUNICODE -g0'
const MediaInfoLib_CXXFLAGS = `-I ../../../Source -I ../../../../ZenLib/Source \
  -DMEDIAINFO_REFERENCES_NO -DMEDIAINFO_FILTER_NO -DMEDIAINFO_DUPLICATE_NO -DMEDIAINFO_MACROBLOCKS_NO \
  -DMEDIAINFO_TRACE_NO -DMEDIAINFO_TRACE_FFV1CONTENT_NO -DMEDIAINFO_IBI_NO -DMEDIAINFO_DIRECTORY_NO -DMEDIAINFO_JNI_NO \
  -DMEDIAINFO_LIBCURL_NO -DMEDIAINFO_LIBMMS_NO -DMEDIAINFO_DVDIF_ANALYZE_NO -DMEDIAINFO_MPEGTS_DUPLICATE_NO \
  -DMEDIAINFO_READTHREAD_NO -DMEDIAINFO_MD5_NO -DMEDIAINFO_SHA1_NO -DMEDIAINFO_SHA2_NO -DMEDIAINFO_EVENTS_NO \
  -DMEDIAINFO_DEMUX_NO -DMEDIAINFO_AES_NO -DMEDIAINFO_FIXITY_NO -DMEDIAINFO_READER_NO -DMEDIAINFO_NEXTPACKET_NO`

export {
  BUILD_DIR,
  CFLAGS,
  CXXFLAGS,
  DIST_DIR,
  LIBMEDIAINFO_VERSION,
  LIBZEN_VERSION,
  MediaInfoLib_CXXFLAGS,
  PROJECT_DIR,
  SRC_DIR,
  VENDOR_DIR,
  ZLIB_DIR,
  ZLIB_VERSION,
}
